### ISSUE TITLE
How to encode to 320k

### ISSUE THREAD

**Issue by creativeWaltz** [jeanslack/FFcuesplitter#13]
Hello 

Love this and working great except defaults to 128 VBR

How do I do 320k convert to mp3. I tried 

` ffcuesplitter -f mp3 -i example.cue --ffmpeg_add_params '-ab 320k'`
and got the error: 

` unrecognized arguments: --ffmpeg_add_params -ab 320k: --ffmpeg_add_params -ab 320k`

Pardon my ignorance and thanks!

**Comment by jeanslack** [comment]
@creativeWaltz 

Hello,
You are using underscore instead of hyphen: `--ffmpeg_add_params`

**Comment by creativeWaltz** [comment]
ah great thanks, the readme shows is as underscore so does that need updating?

**Comment by jeanslack** [comment]
I will have to update the USAGE of the command line, I just realized that it is not correct yet.
