### ISSUE TITLE
local var referenced before assignment error?

### ISSUE THREAD

**Issue by acroyear** [jeanslack/FFcuesplitter#23]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/ffcuesplitter/main.py", line 215, in <module>
    main()
  File "/opt/homebrew/lib/python3.10/site-packages/ffcuesplitter/main.py", line 197, in main
    split.open_cuefile()
  File "/opt/homebrew/lib/python3.10/site-packages/ffcuesplitter/cuesplitter.py", line 407, in open_cuefile
    self.deflacue_object_handler()
  File "/opt/homebrew/lib/python3.10/site-packages/ffcuesplitter/cuesplitter.py", line 329, in deflacue_object_handler
    filename = (f"{sanitize(track[1].title)}")  # title names sanitize
  File "/opt/homebrew/lib/python3.10/site-packages/ffcuesplitter/utils.py", line 52, in sanitize
    newstr.replace('/', '')
UnboundLocalError: local variable 'newstr' referenced before assignment

**Comment by acroyear** [comment]
python 3.10, probably being more picky about initializations when it happens within an 'if'.  I fixed it by

```
    newstr = ''

    if platform.system() == 'Windows':
        newstr = re.sub(r"[\"\*\:\<\>\?\/\|\\]", '', newstr)
    else:
        newstr.replace('/', '')
```

**Comment by acroyear** [comment]
actually it had a second bug for Mac/Linux:

        newstr = newstr.replace('/', '-')

**Comment by acroyear** [comment]
(once that was resolved, it is working great, thanks)

**Comment by agstevens** [comment]
Had the same issues as acroyear on Python 3.11, updated utils.py with his changes, and double checked the paths of ffprobe and ffmpeg and everything worked fine. Thanks

**Comment by jeanslack** [comment]
I haven't tested the program on Python10/11 yet.
I will try to fix the bug as soon as possible.
Thank you all!

**Comment by jeanslack** [comment]
@acroyear 

>  newstr = newstr.replace('/', '-')

Does what you call a bug give you any problems?

**Comment by acroyear** [comment]
yes. "newstr.replace('/', '-')" does not update newstr in python (same as javascript). It returns a new string that in this case was not assigned anywhere. So newstr was not changed, and the "/" caused a file system violation trying to create the file.

The windows version worked because it didn't presume newstr was modified - re.sub returned a new string.

I went with '-' instead of '' empty string because it made file names unreadable if the content didn't have spaces ('x/y' => 'xy'), or it ended up with excess spaces if it did ('x / y' => 'x  y'). i prefer string cleanups to be 1-1 and not 'lossy' in the sense of removing characters, and if i was on a windows system i'd do the same. But I admit that's a matter of preference.
